// <auto-generated />
using System;
using Kolokwium.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240611132308_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium.Models.Backpack_Slots", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<int>("characterID")
                        .HasColumnType("int")
                        .HasColumnName("FK_character");

                    b.Property<int>("itemID")
                        .HasColumnType("int")
                        .HasColumnName("FK_item");

                    b.HasKey("PK");

                    b.HasIndex("characterID");

                    b.HasIndex("itemID");

                    b.ToTable("Backpack_Slots");
                });

            modelBuilder.Entity("Kolokwium.Models.Character_Titles", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int")
                        .HasColumnName("FK_charact");

                    b.Property<int>("TitleID")
                        .HasColumnType("int")
                        .HasColumnName("FK_title");

                    b.Property<DateTime>("aquire_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("aquire_at");

                    b.HasKey("CharacterID", "TitleID");

                    b.HasIndex("TitleID");

                    b.ToTable("Character_Titles");
                });

            modelBuilder.Entity("Kolokwium.Models.Characters", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<int>("current_weig")
                        .HasColumnType("int")
                        .HasColumnName("current_weig");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("max_weight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<int>("money")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.HasKey("PK");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Kolokwium.Models.Items", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("weig")
                        .HasColumnType("int")
                        .HasColumnName("weig");

                    b.HasKey("PK");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Kolokwium.Models.Titles", b =>
                {
                    b.Property<int>("PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nam");

                    b.HasKey("PK");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Kolokwium.Models.Backpack_Slots", b =>
                {
                    b.HasOne("Kolokwium.Models.Characters", "Characters")
                        .WithMany("Backpack_Slots")
                        .HasForeignKey("characterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Items", "Items")
                        .WithMany("Backpack_Slots")
                        .HasForeignKey("itemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characters");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kolokwium.Models.Character_Titles", b =>
                {
                    b.HasOne("Kolokwium.Models.Characters", "Characters")
                        .WithMany("Character_Titles")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Titles", "Titles")
                        .WithMany("Character_Titles")
                        .HasForeignKey("TitleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characters");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Kolokwium.Models.Characters", b =>
                {
                    b.Navigation("Backpack_Slots");

                    b.Navigation("Character_Titles");
                });

            modelBuilder.Entity("Kolokwium.Models.Items", b =>
                {
                    b.Navigation("Backpack_Slots");
                });

            modelBuilder.Entity("Kolokwium.Models.Titles", b =>
                {
                    b.Navigation("Character_Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
